db.driver=com.mysql.cj.jdbc.Driver
db.host=jdbc:mysql://database-2.clu86ciqwgsi.ap-south-1.rds.amazonaws.com/admin
db.port=3306
db.name=onlinebookstore
db.username=admin
db.password=6432OyWwfkL2093Fwl6x
